// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKXrDsmynULb3ql2fz63AEOwmmAWEBiLo',
    appId: '1:721782087228:web:b1caedc0b21e62e72d2d39',
    messagingSenderId: '721782087228',
    projectId: 'ecfile-ecpaye',
    authDomain: 'ecfile-ecpaye.firebaseapp.com',
    storageBucket: 'ecfile-ecpaye.appspot.com',
    measurementId: 'G-XSYB8CY2GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxN4GwDcIPlc-D_VVoXNFaWHEMLyrnflI',
    appId: '1:721782087228:android:5666ade0d71b0d9b2d2d39',
    messagingSenderId: '721782087228',
    projectId: 'ecfile-ecpaye',
    storageBucket: 'ecfile-ecpaye.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOgnbKFUzGo6JfqFby8pYR96vVnGMpiVQ',
    appId: '1:721782087228:ios:8cf4bf5668be5d042d2d39',
    messagingSenderId: '721782087228',
    projectId: 'ecfile-ecpaye',
    storageBucket: 'ecfile-ecpaye.appspot.com',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOgnbKFUzGo6JfqFby8pYR96vVnGMpiVQ',
    appId: '1:721782087228:ios:1fcfb5e99b2e824b2d2d39',
    messagingSenderId: '721782087228',
    projectId: 'ecfile-ecpaye',
    storageBucket: 'ecfile-ecpaye.appspot.com',
    iosBundleId: 'com.example.flutterfire.RunnerTests',
  );
}
